# Generated by Django 2.0.1 on 2018-04-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzh', '0003_auto_20180419_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalid_task_url',
            name='create_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='invalid_task_url',
            name='input_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task_url',
            name='create_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='task_url',
            name='input_time',
            field=models.DateTimeField(default=None),
        ),
    ]
