# Generated by Django 2.0.1 on 2018-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzh', '0004_auto_20180419_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invalid_task_url',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invalid_task_url',
            name='input_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task_url',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task_url',
            name='input_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
