# Generated by Django 2.0.1 on 2018-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fail_url_detail',
            name='dept_name_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
