# Generated by Django 2.0.1 on 2018-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzh', '0002_fail_url_detail_dept_name_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_url',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task_url',
            name='input_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
