# Generated by Django 2.0.1 on 2018-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zzh', '0005_auto_20180419_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fail_url_detail',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
